### ISSUE TITLE
Undefined colour variable "yellow"

### ISSUE THREAD

**Issue by Souhitya-chaudhuri** [lighthaus-theme/vim-lighthaus#1]
It seems the colour yellow has not been defined but called nonetheless and that's throwing the error.
![Screenshot_20210227_154539](https://user-images.githubusercontent.com/38003167/109384543-8d7c3880-7913-11eb-9cba-ef17b2ee930e.jpg)

**Comment by lighthaus-theme** [comment]
You are right, my bad.

Was leftover from when I was naming colors differently and I didn't correct it.

Just pushed the corrected version. Hope it works now.
